### ISSUE TITLE
Add Kor UI setting

### ISSUE THREAD

**Issue by Kesim** [Kesim/notepad#1]
Make ko-KR.rc file at notepad/lang.
After make it, add setting in rsrc.rc file

**Comment by ShimGyurim** [comment]
Printing functionality doesn't correctly operate. Need to fix it.

**Comment by Kesim** [comment]
> ada7bbb64f91b1ee5eba706ba426a85b51796c7a
I add ko-KR.rc file, and fix rsrc.rc to set Korean UI.
And I can open 'notepad info' tap. In zh-CN.rc or rsrc.rc maybe is problem.
-p.s link is fixed

**Comment by Kesim** [comment]
If you want return UI language, fix
`//#define LANGUAGE_ZH_CN
#define LANGUAGE_KO_KR` 
to
`#define LANGUAGE_ZH_CN
//#define LANGUAGE_KO_KR`
in rsrc.rc

**Comment by ShimGyurim** [comment]
commit link cannot open

**Comment by Kesim** [comment]
We did it. #23
