### ISSUE TITLE
Fix printer button

### ISSUE THREAD

**Issue by Kesim** [Kesim/notepad#2]
I found a problem that don't be shown printer button in page setup tap.
And I fix
`    PUSHBUTTON "프린터(&P)...", psh3, 310, 170, 50, 14 `
to
`    PUSHBUTTON "프린터(&P)...", psh1, 310, 170, 50, 14`
in ko-KR.rc.
After fix that, I can show printer button.
We fix all .rc file at /notepad/lang

**Comment by ShimGyurim** [comment]
In the other languages, are We need to fix it manually?

**Comment by Kesim** [comment]
> 
> 
> In the other languages, are We need to fix it manually?

Fix all of .rc file in /notepad/lang or add comment of this problem at rsrc.rc file.

**Comment by Kesim** [comment]
#19 #20 
This problem solved.
Fix button in ko-KR, zh-CN, en-US and leave FIXME comment at rsrc.rc.
So, I'll closed this issue.
